# Generated by Django 6.0.7 on 2026-09-01 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAnalysisCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField()),
                ('provider_called_at', models.DateTimeField(blank=True, null=True)),
                ('quota_debited_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('provider_request_id', models.CharField(blank=True, max_length=255)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True)),
                ('failure_category', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_analysis_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'quota_debited_at'], name='ai_call_user_quota_at'), models.Index(fields=['user', 'created_at'], name='ai_call_user_created_at')],
            },
        ),
    ]
