# Generated by Django 6.0.7 on 2026-08-20 23:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dietary_constraints',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_timeline_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(104)]),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20')), django.core.validators.MaxValueValidator(Decimal('400'))]),
        ),
        migrations.AddField(
            model_name='user',
            name='training_days_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
