# Generated by Django 6.0.7 on 2026-08-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pounds_and_onboarding_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
