#!/usr/bin/env node
/**
 * Mirrors the Linear project's planning documents into `plans/`.
 *
 *   pnpm sync:plans
 *
 * Linear is the source of truth for planning (see plans/00-app-overview.md).
 * The repo copy exists so a Claude Code session has the docs in context without
 * a round trip. Before this script, the mirror was hand-copied once and then
 * drifted for a month — nine of twelve docs were stale, several describing
 * decisions that had since been reversed.
 *
 * Everything this script writes is build output. Do not hand-edit it: change
 * the Linear doc and run the command again.
 *
 * `plans/tickets/` is the exception. Doc 03 requires approved implementation
 * plans to be committed there alongside the work, so it is hand-written and
 * this script never reads, writes, or prunes inside it.
 *
 * Deliberately not wired into CI as a drift gate. The api-client drift check
 * works because its source and output both live in the repo, so only your own
 * PR can break it. These docs drift when someone edits Linear, which has
 * nothing to do with whatever PR is open — a hard gate there would turn
 * unrelated PRs red. A scheduled job that opens a PR is the right shape.
 */

import { existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const LINEAR_API = "https://api.linear.app/graphql";

// The Macros Tracker Native project. Overridable so the script is testable
// against another project without editing it.
const PROJECT_ID = process.env.LINEAR_PROJECT_ID ?? "de781164-e203-4f20-8ca6-dc7b6763b160";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PLANS_DIR = path.join(REPO_ROOT, "plans");
const ARCHIVE_DIR = path.join(PLANS_DIR, "archive");
const LEGACY_DESIGN_DIR = path.join(PLANS_DIR, "design");
const TICKETS_DIR = path.join(PLANS_DIR, "tickets");

const QUERY = `
  query ProjectDocuments($id: String!) {
    project(id: $id) {
      name
      url
      documents(first: 250) {
        nodes {
          id
          title
          content
          url
          updatedAt
        }
      }
    }
  }
`;

/**
 * "01 — Architecture & Repo Structure" -> "01-architecture-and-repo-structure"
 *
 * Filenames come from the Linear title rather than a lookup table on purpose.
 * A hand-maintained title-to-filename map is one more thing that rots, and
 * rotting mappings are the problem this script exists to solve.
 */
function slugify(title) {
  return title
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Linear signs uploaded-image URLs with a five-minute expiry, so a mirrored
 * embed is a dead link before the commit lands. Drop the embed and point at
 * the Linear doc, which the frontmatter carries.
 */
function stripImages(markdown) {
  return markdown.replace(/!\[[^\]]*\]\([^)]*\)/g, "_[image omitted — see the Linear doc]_");
}

function buildFile(doc) {
  const frontmatter = [
    "---",
    `linear_id: ${doc.id}`,
    `linear_title: ${JSON.stringify(doc.title)}`,
    `linear_url: ${doc.url}`,
    `linear_updated_at: ${doc.updatedAt}`,
    "generated: true",
    "---",
    "",
    "<!-- Generated by scripts/sync-plans.mjs. Do not edit: change the Linear doc",
    "     and run `pnpm sync:plans`. -->",
    "",
    "",
  ].join("\n");

  return `${frontmatter}${stripImages(doc.content ?? "")}\n`;
}

function buildReadme(entries, project) {
  const row = (e) => `| [${e.title}](${e.relPath}) | [Linear](${e.url}) |`;

  const canonical = entries.filter((e) => e.canonical);
  const archived = entries.filter((e) => !e.canonical);

  const section = (heading, rows) =>
    rows.length
      ? [`## ${heading}`, "", "| Doc | Source |", "| -- | -- |", ...rows.map(row), ""]
      : [];

  return [
    "<!-- Generated by scripts/sync-plans.mjs. Do not edit. -->",
    "",
    `# Plans`,
    "",
    `Mirror of the [${project.name}](${project.url}) planning documents in Linear.`,
    "",
    "**Everything here except `tickets/` is generated.** Do not hand-edit it —",
    "change the Linear doc and run `pnpm sync:plans`.",
    "",
    "## Source-of-truth order",
    "",
    "1. Alex is the final source of truth for product clarification.",
    "2. START HERE and CANONICAL documents define current requirements.",
    "3. Active Linear milestones and issues define the current slice.",
    "4. Approved `tickets/` plans describe an accepted implementation.",
    "5. The repository and tests describe behavior that already exists.",
    "",
    "**Never use a document under `archive/` to plan or implement work.** These",
    "files preserve history and can contain detailed requirements that were reversed.",
    "",
    ...section("Canonical", canonical),
    ...section("Archived history. Do not use for implementation", archived),
  ].join("\n");
}

async function fetchDocuments() {
  const apiKey = process.env.LINEAR_API_KEY;
  if (!apiKey) {
    throw new Error(
      "LINEAR_API_KEY is not set.\n" +
        "Create one at Linear → Settings → Security & access:\n" +
        "  https://linear.app/settings/account/security\n" +
        "Read-only scope is enough. Add it to .env as LINEAR_API_KEY=lin_api_...",
    );
  }

  const res = await fetch(LINEAR_API, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: apiKey },
    body: JSON.stringify({ query: QUERY, variables: { id: PROJECT_ID } }),
  });

  if (!res.ok) {
    throw new Error(`Linear API returned ${res.status} ${res.statusText}`);
  }

  const json = await res.json();
  if (json.errors?.length) {
    throw new Error(`Linear API error: ${json.errors.map((e) => e.message).join("; ")}`);
  }
  if (!json.data?.project) {
    throw new Error(`No project found for id ${PROJECT_ID}`);
  }

  return json.data.project;
}

/**
 * Delete generated files this run did not write, so a doc renamed or deleted in
 * Linear does not linger in the repo. The old `design/` directory is swept too
 * because the revamp moved every non-canonical document under `archive/`.
 * Only generated .md files are removed. `tickets/` is never touched.
 */
async function pruneOrphans(dir, keep) {
  if (!existsSync(dir)) return [];

  const pruned = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    const full = path.join(dir, entry.name);
    if (keep.has(full)) continue;
    await rm(full);
    pruned.push(path.relative(REPO_ROOT, full));
  }
  return pruned;
}

async function main() {
  const project = await fetchDocuments();
  const documents = project.documents.nodes;

  if (documents.length === 0) {
    throw new Error("Project returned zero documents — refusing to prune the mirror.");
  }

  await mkdir(ARCHIVE_DIR, { recursive: true });

  const written = new Set();
  const entries = [];

  for (const doc of documents) {
    const canonical = doc.title.startsWith("START HERE") || doc.title.startsWith("CANONICAL");
    const dir = canonical ? PLANS_DIR : ARCHIVE_DIR;
    const fullPath = path.join(dir, `${slugify(doc.title)}.md`);

    await writeFile(fullPath, buildFile(doc), "utf8");
    written.add(fullPath);

    entries.push({
      canonical,
      title: doc.title,
      url: doc.url,
      relPath: `./${path.relative(PLANS_DIR, fullPath)}`,
    });
  }

  entries.sort((a, b) => {
    if (a.canonical !== b.canonical) return a.canonical ? -1 : 1;
    return a.title.localeCompare(b.title);
  });

  const readmePath = path.join(PLANS_DIR, "README.md");
  await writeFile(readmePath, `${buildReadme(entries, project)}\n`, "utf8");
  written.add(readmePath);

  const pruned = [
    ...(await pruneOrphans(PLANS_DIR, written)),
    ...(await pruneOrphans(ARCHIVE_DIR, written)),
    ...(await pruneOrphans(LEGACY_DESIGN_DIR, written)),
  ];

  console.log(`Synced ${documents.length} documents from "${project.name}".`);
  if (pruned.length) {
    console.log(`Pruned ${pruned.length} stale file(s):`);
    for (const file of pruned) console.log(`  ${file}`);
  }
  if (existsSync(TICKETS_DIR)) {
    console.log("Left plans/tickets/ untouched (hand-written, see doc 03).");
  }
}

main().catch((error) => {
  console.error(`\nsync-plans failed: ${error.message}\n`);
  process.exit(1);
});
