/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Health,
  Ping,
  PresignUploadRequestRequest,
  PresignUploadResponse,
  Session,
  SessionCreateRequest,
} from "./model";

import { customFetch } from "../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Exchanges a verified Apple identity token for a user and a JWT pair. Creates the account when the Apple subject is unknown, so this one call covers both first-time sign-up and returning login.

**Nonce.** Send the *raw* nonce, not the digest. The client sets `SHA256(nonce)` as lowercase hex on the Apple request and Apple copies that digest into the token; the server hashes the raw value to compare. Sending the digest fails verification.

**Name.** Apple supplies `fullName` on the first authorization only. Send it when present; omitting it never clears a stored name. It is not part of the signed token, so it is stored for display and is not verified.

**Reactivation.** A previously deleted account is restored automatically, with no time limit. Once the purge has removed the row, a sign-in creates a fresh account instead.

Requires no authentication, and is rate limited by IP. Every verification failure returns the same 401 regardless of cause.
 * @summary Sign in with Apple
 */
export type createSessionResponse201 = {
  data: Session;
  status: 201;
};

export type createSessionResponse400 = {
  data: void;
  status: 400;
};

export type createSessionResponse401 = {
  data: void;
  status: 401;
};

export type createSessionResponse429 = {
  data: void;
  status: 429;
};

export type createSessionResponseSuccess = createSessionResponse201 & {
  headers: Headers;
};
export type createSessionResponseError = (
  createSessionResponse400 | createSessionResponse401 | createSessionResponse429
) & {
  headers: Headers;
};

export type createSessionResponse = createSessionResponseSuccess | createSessionResponseError;

export const getCreateSessionUrl = () => {
  return `/api/auth/sessions/`;
};

export const createSession = async (
  sessionCreateRequest: SessionCreateRequest,
  options?: RequestInit,
): Promise<createSessionResponse> => {
  return customFetch<createSessionResponse>(getCreateSessionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sessionCreateRequest),
  });
};

export const getCreateSessionMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSession>>,
    TError,
    { data: SessionCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSession>>,
  TError,
  { data: SessionCreateRequest },
  TContext
> => {
  const mutationKey = ["createSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSession>>,
    { data: SessionCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createSession(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createSession>>>;
export type CreateSessionMutationBody = SessionCreateRequest;
export type CreateSessionMutationError = void;

/**
 * @summary Sign in with Apple
 */
export const useCreateSession = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSession>>,
      TError,
      { data: SessionCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSession>>,
  TError,
  { data: SessionCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Reports whether the API can serve traffic. Unlike `/api/ping/`, this executes a real query against the database and returns HTTP 503 if that query fails, so an orchestrator can pull the instance out of rotation. Requires no authentication.

Intended for platform health probes rather than for clients.
 * @summary Deployment health check
 */
export type healthResponse200 = {
  data: Health;
  status: 200;
};

export type healthResponse503 = {
  data: Health;
  status: 503;
};

export type healthResponseSuccess = healthResponse200 & {
  headers: Headers;
};
export type healthResponseError = healthResponse503 & {
  headers: Headers;
};

export type healthResponse = healthResponseSuccess | healthResponseError;

export const getHealthUrl = () => {
  return `/api/health/`;
};

export const health = async (options?: RequestInit): Promise<healthResponse> => {
  return customFetch<healthResponse>(getHealthUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthQueryKey = () => {
  return [`/api/health/`] as const;
};

export const getHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof health>>,
  TError = Health,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({ signal }) =>
    health({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof health>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type HealthQueryError = Health;

export function useHealth<TData = Awaited<ReturnType<typeof health>>, TError = Health>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof health>>,
          TError,
          Awaited<ReturnType<typeof health>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHealth<TData = Awaited<ReturnType<typeof health>>, TError = Health>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof health>>,
          TError,
          Awaited<ReturnType<typeof health>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHealth<TData = Awaited<ReturnType<typeof health>>, TError = Health>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Deployment health check
 */

export function useHealth<TData = Awaited<ReturnType<typeof health>>, TError = Health>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns a small fixed-shape payload confirming the API is reachable and able to serialize a response. Requires no authentication and touches no database, so it is safe to call from an unauthenticated client and as a container health check.
 * @summary API liveness probe
 */
export type pingResponse200 = {
  data: Ping;
  status: 200;
};

export type pingResponseSuccess = pingResponse200 & {
  headers: Headers;
};
export type pingResponse = pingResponseSuccess;

export const getPingUrl = () => {
  return `/api/ping/`;
};

export const ping = async (options?: RequestInit): Promise<pingResponse> => {
  return customFetch<pingResponse>(getPingUrl(), {
    ...options,
    method: "GET",
  });
};

export const getPingQueryKey = () => {
  return [`/api/ping/`] as const;
};

export const getPingQueryOptions = <
  TData = Awaited<ReturnType<typeof ping>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof ping>>, TError, TData>>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPingQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof ping>>> = ({ signal }) =>
    ping({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof ping>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PingQueryResult = NonNullable<Awaited<ReturnType<typeof ping>>>;
export type PingQueryError = unknown;

export function usePing<TData = Awaited<ReturnType<typeof ping>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof ping>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ping>>,
          TError,
          Awaited<ReturnType<typeof ping>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePing<TData = Awaited<ReturnType<typeof ping>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof ping>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ping>>,
          TError,
          Awaited<ReturnType<typeof ping>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePing<TData = Awaited<ReturnType<typeof ping>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof ping>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary API liveness probe
 */

export function usePing<TData = Awaited<ReturnType<typeof ping>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof ping>>, TError, TData>>;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPingQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns a short-lived presigned PUT URL and the object key the upload will land at.

The client uploads straight to object storage rather than through this API, so a slow mobile connection never occupies a server worker. The declared content type and length are signed into the URL: the subsequent PUT must match both exactly or storage rejects it.

Store the returned `key` against the entry. The URL expires; the key does not.
 * @summary Authorise a direct photo upload
 */
export type presignUploadResponse200 = {
  data: PresignUploadResponse;
  status: 200;
};

export type presignUploadResponse400 = {
  data: void;
  status: 400;
};

export type presignUploadResponse401 = {
  data: void;
  status: 401;
};

export type presignUploadResponseSuccess = presignUploadResponse200 & {
  headers: Headers;
};
export type presignUploadResponseError = (presignUploadResponse400 | presignUploadResponse401) & {
  headers: Headers;
};

export type presignUploadResponse = presignUploadResponseSuccess | presignUploadResponseError;

export const getPresignUploadUrl = () => {
  return `/api/uploads/`;
};

export const presignUpload = async (
  presignUploadRequestRequest: PresignUploadRequestRequest,
  options?: RequestInit,
): Promise<presignUploadResponse> => {
  return customFetch<presignUploadResponse>(getPresignUploadUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(presignUploadRequestRequest),
  });
};

export const getPresignUploadMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof presignUpload>>,
    TError,
    { data: PresignUploadRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof presignUpload>>,
  TError,
  { data: PresignUploadRequestRequest },
  TContext
> => {
  const mutationKey = ["presignUpload"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof presignUpload>>,
    { data: PresignUploadRequestRequest }
  > = (props) => {
    const { data } = props ?? {};

    return presignUpload(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PresignUploadMutationResult = NonNullable<Awaited<ReturnType<typeof presignUpload>>>;
export type PresignUploadMutationBody = PresignUploadRequestRequest;
export type PresignUploadMutationError = void;

/**
 * @summary Authorise a direct photo upload
 */
export const usePresignUpload = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof presignUpload>>,
      TError,
      { data: PresignUploadRequestRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof presignUpload>>,
  TError,
  { data: PresignUploadRequestRequest },
  TContext
> => {
  const mutationOptions = getPresignUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
