/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `sedentary` - sedentary
 * `light` - light
 * `moderate` - moderate
 * `very_active` - very_active
 */
export type ActivityEnum = (typeof ActivityEnum)[keyof typeof ActivityEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityEnum = {
  sedentary: "sedentary",
  light: "light",
  moderate: "moderate",
  very_active: "very_active",
} as const;
