/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import type { DayTargets } from "./dayTargets";
import type { FoodEntry } from "./foodEntry";

export interface Day {
  local_date: string;
  /** @nullable */
  targets: DayTargets;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  calories: string;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  protein_g: string;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  fiber_g: string;
  entries: FoodEntry[];
}
