/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import type { ManualEntryCreateRequest } from "./manualEntryCreateRequest";
import type { PhotoEntryCreateRequest } from "./photoEntryCreateRequest";

export type EntryCreateRequestRequest = ManualEntryCreateRequest | PhotoEntryCreateRequest;
