/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Stable rolling-quota response for the food analysis endpoint.
 */
export interface FoodAnalysisQuotaError {
  readonly code: string;
  detail: string;
  /** @minimum 1 */
  limit: number;
  /** @minimum 0 */
  used: number;
  readonly window_days: number;
  retry_at: string;
}
