/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

export interface FoodAnalysisItem {
  /** @maxLength 200 */
  name: string;
  /** @maxLength 100 */
  portion: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  calories: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  protein_g: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  fiber_g: string;
}
