/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `cut` - cut
 * `maintain` - maintain
 * `gain` - gain
 */
export type GoalEnum = (typeof GoalEnum)[keyof typeof GoalEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoalEnum = {
  cut: "cut",
  maintain: "maintain",
  gain: "gain",
} as const;
