/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import type { HealthStatusEnum } from "./healthStatusEnum";

/**
 * Response body for the deployment health check.

Distinct from `PingSerializer` on purpose. Ping answers "is the process
up?"; health answers "can this process actually serve a request?", which
means proving the database is reachable. They report different things and a
shared shape would blur that.
 */
export interface Health {
  /** `ok` when every dependency check passed, `unhealthy` otherwise. An `unhealthy` body is always served with HTTP 503, never 200.

* `ok` - ok
* `unhealthy` - unhealthy */
  status: HealthStatusEnum;
  /** Whether a real query against the default database succeeded. This is an executed round-trip, not a check that settings are present. */
  database: boolean;
  /** API version string, mirroring SPECTACULAR_SETTINGS['VERSION']. */
  version: string;
  /** Server time in UTC (ISO 8601) when the check was performed. */
  timestamp: string;
}
