/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `ok` - ok
 * `unhealthy` - unhealthy
 */
export type HealthStatusEnum = (typeof HealthStatusEnum)[keyof typeof HealthStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthStatusEnum = {
  ok: "ok",
  unhealthy: "unhealthy",
} as const;
