/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import { SexEnum } from "./sexEnum";
import { BlankEnum } from "./blankEnum";

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchedUserSettingsRequestSex = { ...SexEnum, ...BlankEnum } as const;
