/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * What a client may write to its own user.

Deliberately not `UserSerializer` with a couple of fields marked read-only.
Sharing one serializer between the read and the write shape is how
`onboarding_completed` becomes client-settable: it only takes someone
relaxing a `read_only_fields` entry to ship the hole, and nothing about the
read shape would look wrong in review.

Bounds live on the model fields, so `PATCH` and the admin reject the same
values. ModelSerializer copies model validators onto the serializer fields.
 */
export interface PatchedUserSettingsRequest {
  /**
   * IANA timezone name, e.g. `America/New_York`. The client refreshes this on launch (doc 02), so a user who flies somewhere gets their days bucketed locally. Never a numeric offset — offsets break across DST.
   * @minLength 1
   * @maxLength 64
   */
  timezone?: string;
  /**
   * Target body weight in kilograms, 20–400. Null clears it back to unanswered.
   * @nullable
   * @pattern ^-?\d{0,3}(?:\.\d{0,2})?$
   */
  goal_weight_kg?: string | null;
  /**
   * Weeks the user wants to reach the goal weight in, 1–104. A duration rather than a date, so it does not go stale. Null clears.
   * @minimum 1
   * @maximum 104
   * @nullable
   */
  goal_timeline_weeks?: number | null;
  /**
   * Training days in a typical week, 0–7. Null clears.
   * @minimum 0
   * @maximum 7
   * @nullable
   */
  training_days_per_week?: number | null;
  /**
   * Free text, up to 500 characters — 'no dairy, allergic to shellfish'. Read by the advice feature (doc 08), not by target generation. Send an empty string to clear; null is accepted and stored as empty.
   * @maxLength 500
   * @nullable
   */
  dietary_constraints?: string | null;
}
