/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

export interface PhotoEntryCreateRequest {
  local_date: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  timezone: string;
  eaten_at: string;
  /** @minimum 1 */
  analysis_id: number;
}
