/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response body for the API liveness probe.

Fields are declared explicitly (never `fields = "__all__"`) so the emitted
OpenAPI schema is precise enough to generate useful client types from.
 */
export interface Ping {
  /** Always `ok` when the API is reachable. */
  status: string;
  /** API version string, mirroring SPECTACULAR_SETTINGS['VERSION']. */
  version: string;
  /** Server time in UTC (ISO 8601) when the request was handled. */
  timestamp: string;
}
