/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * The signed authorisation handed back to the client.
 */
export interface PresignUploadResponse {
  /** Presigned S3 PUT URL. Treat as a credential: anyone holding it can upload to this key until it expires. */
  url: string;
  /** Object key the upload will land at. Store this against the entry — it is the durable identifier, whereas the URL expires. */
  key: string;
  /** Seconds until the URL stops being accepted. */
  expires_in: number;
  /** Server-side upload ceiling, echoed so a client can fail fast locally instead of discovering it on a rejected PUT. */
  max_bytes: number;
}
