/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * What the client must state before an upload is authorised.

Both fields are required. Letting either default would mean signing a URL
whose constraints the client never committed to, which is the same as not
constraining it.
 */
export interface PresignUploadRequestRequest {
  /**
   * MIME type of the file about to be uploaded. Must be one of the supported image types; the PUT is rejected if it does not match.
   * @minLength 1
   */
  content_type: string;
  /**
   * Exact size in bytes of the file about to be uploaded. Signed into the URL, so the PUT must send precisely this many bytes.
   * @minimum 1
   */
  content_length: number;
}
