/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

export interface RecentEntryCreateRequest {
  local_date: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  timezone: string;
  eaten_at: string;
  /** @minimum 1 */
  recent_item_id: number;
  /** @pattern ^-?\d{0,6}(?:\.\d{0,2})?$ */
  quantity: string;
}
