/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * What the client presents to sign in.

Both fields are required. The token alone is not enough: without the nonce
there is nothing to prove this token was minted for *this* sign-in attempt
rather than captured from an earlier one.
 */
export interface SessionCreateRequest {
  /**
   * The `identityToken` from ASAuthorizationAppleIDCredential, as a JWT string. Verified against Apple's published signing keys before anything else happens.
   * @minLength 1
   */
  identity_token: string;
  /**
   * The **raw** nonce generated for this sign-in, not the digest. The client sets `SHA256(nonce)` as lowercase hex on the Apple request; Apple copies that digest into the token verbatim, and the server hashes this value to compare. Sending the digest here fails.
   * @minLength 1
   */
  nonce: string;
  /**
   * Display name, from `fullName` on the credential. Apple supplies it on the first authorization only and never again, so send it when present and omit it otherwise — omitting never clears a stored name. Unverified: Apple puts no name in the identity token, so this is the client's word and is used for display only.
   * @maxLength 255
   */
  name?: string;
}
