/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * What sign-out presents.

The refresh token, in the body of a DELETE. Unusual, and correct: an access
token cannot be revoked -- there is no blacklist on the access path -- so
the refresh token is the only thing there is to destroy.
 */
export interface SessionDeleteRequest {
  /**
   * The refresh token to blacklist. Must belong to the authenticated user; another user's token is rejected.
   * @minLength 1
   */
  refresh: string;
}
