/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A refresh token in, a new token pair out.

One serializer for both directions, because the shapes match. `access` is
response-only, so the request component drops it.
 */
export interface SessionRefresh {
  /** The refresh token from the last sign-in or refresh. It is the credential for this call: no `Authorization` header is read, because the whole point of refreshing is that the access token has expired.

The response contains a **different** refresh token. Store it, and discard the one you sent -- rotation blacklists it immediately. */
  refresh: string;
  /** A new short-lived access token. */
  readonly access: string;
}
