/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * The signed-in user, as the client needs them.

A deliberate subset. The mobile app routes on `onboarding_completed` and
displays the rest; nothing else on the model is its business.
 */
export interface SessionUser {
  /** Stable user identifier. */
  id: number;
  /**
   * May be null: Apple does not guarantee an email, and may supply a private relay address rather than a real one.
   * @nullable
   */
  email: string | null;
  /** Display name, or empty when Apple never supplied one. */
  name: string;
  /** Whether the client should route to onboarding or to Today. */
  onboarding_completed: boolean;
  /** IANA timezone name, e.g. `America/New_York`. */
  timezone: string;
}
