/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * **Clear it with an empty string, not with `null`.** Every other clearable field here takes `null`; this one is a blank-string column and takes `""`. A form that clears itself by sending `null` everywhere gets a 400 on this field alone.

* `female` - Female
* `male` - Male
 */
export type SexEnum = (typeof SexEnum)[keyof typeof SexEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SexEnum = {
  female: "female",
  male: "male",
} as const;
