/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `onboarding_ai` - Onboarding (AI proposal)
 * `manual` - Manual edit
 */
export type SourceEnum = (typeof SourceEnum)[keyof typeof SourceEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourceEnum = {
  onboarding_ai: "onboarding_ai",
  manual: "manual",
} as const;
