/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `onboarding` - Onboarding
 * `manual` - Manual edit
 */
export type TargetVersionSourceEnum =
  (typeof TargetVersionSourceEnum)[keyof typeof TargetVersionSourceEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TargetVersionSourceEnum = {
  onboarding: "onboarding",
  manual: "manual",
} as const;
