/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Three numbers, with no identity of their own.
 */
export interface Targets {
  readonly calories: number;
  readonly protein_g: number;
  readonly fiber_g: number;
}
