/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import type { TargetVersionSourceEnum } from "./targetVersionSourceEnum";

export interface TargetVersion {
  readonly id: number;
  /** Daily calorie target, kcal. */
  readonly calories: number;
  /** Daily protein target, in grams. */
  readonly protein_g: number;
  /** Daily fiber target, in grams. */
  readonly fiber_g: number;
  readonly source: TargetVersionSourceEnum;
  /** Plain-English explanation of the numbers, shown under WHY THESE NUMBERS on screen 9f. Around 60 words, naming the deficit, the rate, and why protein is set from body weight. Empty for a manual edit. */
  readonly rationale: string;
  readonly effective_from: string;
  readonly created_at: string;
}
