/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import type { TargetProposalRequestSexEnum } from "./targetProposalRequestSexEnum";
import type { GoalEnum } from "./goalEnum";
import type { ActivityEnum } from "./activityEnum";

/**
 * The six onboarding answers.

**Pounds and inches**, the units every screen shows. `services` converts to
metric once, inside Mifflin-St Jeor, because that formula is the only thing
in this stack that wants it.

A plain `Serializer`, not a `ModelSerializer`. None of these six is a column:
four are transient inputs to a calculation, and the two that are stored
(`sex`, `current_weight_lb`) belong to `accounts` and are written through a
different endpoint. A `ModelSerializer` here would imply a model that does
not exist.
 */
export interface TargetProposalRequestRequest {
  /**
   * Age in years, 13-100. Mifflin-St Jeor reads it directly. The bounds are data sanity rather than a policy on who may use the app.
   * @minimum 13
   * @maximum 100
   */
  age: number;
  /** Biological sex, `female` or `male`. Biological rather than gender: it is the constant term in a formula fitted to body composition. Stored on the user by `PATCH /api/users/me/`, because editing targets later needs it.

* `female` - female
* `male` - male */
  sex: TargetProposalRequestSexEnum;
  /**
   * Height in inches, 36-96. One number, not feet plus inches: the client shows `5'11"` and sends 71.
   * @minimum 36
   * @maximum 96
   */
  height_in: number;
  /**
   * Body weight in pounds, 85-500. **A hard precondition, not a sanity check.** Outside this band the suggested calorie floor and ceiling cross and the range inverts.
   * @pattern ^-?\d{0,4}(?:\.\d{0,2})?$
   */
  weight_lb: string;
  /** `cut`, `maintain`, or `gain`. Moves calories by a percentage of maintenance rather than a fixed number, and picks the protein figure.

* `cut` - cut
* `maintain` - maintain
* `gain` - gain */
  goal: GoalEnum;
  /** Movement outside deliberate training: `sedentary`, `light`, `moderate`, or `very_active`. A desk job is sedentary even for someone who trains hard, which is the most common way people overstate their burn.

* `sedentary` - sedentary
* `light` - light
* `moderate` - moderate
* `very_active` - very_active */
  activity: ActivityEnum;
}
