/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */

export interface TargetVersionCreateRequest {
  /**
   * Daily calorie target, kcal.
   * @minimum -2147483648
   * @maximum 2147483647
   */
  calories: number;
  /**
   * Daily protein target, in grams.
   * @minimum -2147483648
   * @maximum 2147483647
   */
  protein_g: number;
  /**
   * Daily fiber target, in grams.
   * @minimum -2147483648
   * @maximum 2147483647
   */
  fiber_g: number;
  effective_from: string;
}
