/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import type { Targets } from "./targets";

/**
 * What the formula produced, what it was held to, and why.

`baseline` is kept beside `targets` so doc 15's result screen can show
`BASELINE 2180 -> SET 2150`. The two are equal for almost everyone, and the
screen shows the line only when they differ.

Nothing is persisted. The user accepts a proposal by posting it to
`/api/targets/`, which is where a `TargetVersion` gets created.
 */
export interface TargetProposal {
  readonly targets: Targets;
  /** What the formula produced before the guardrails saw it. Equal to `targets` unless `clamped` is true. */
  readonly baseline: Targets;
  /** Whether a guardrail moved any of the three numbers. Show the baseline beside the target when true, and nothing when false. */
  readonly clamped: boolean;
  /** Around 60 words explaining the numbers, for WHY THESE NUMBERS on screen 9f. Written from a template rather than by a model, so every figure in it is one of the numbers returned beside it. */
  readonly rationale: string;
}
