/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Macros Tracker API
 * Typed contract consumed by apps/mobile via packages/api-client.
 * OpenAPI spec version: 0.1.0
 */
import type { UserSex } from "./userSex";

/**
 * The signed-in user, as the client is allowed to see them.

One serializer for the whole read shape, used by `GET /api/users/me/` and
embedded in the sign-in response. Two serializers describing the same row
would generate two client types that drift the first time a field is added
to one of them.

A ModelSerializer here, and a hand-written Serializer for the request shapes
below. The difference is what the fields are: these mirror model columns and
the validators belong on the model, while a refresh token is not a column
and never will be.

Every field is read-only. This is the *read* shape; the subset a client may
write is `UserSettingsSerializer`, and keeping them apart is what stops a
client from setting `onboarding_completed` on itself.
 */
export interface User {
  readonly id: number;
  /**
   * May be null: Apple does not guarantee an email, and may supply a private relay address rather than a real one.
   * @nullable
   */
  readonly email: string | null;
  /** Display name, or empty when Apple never supplied one. */
  readonly name: string;
  readonly timezone: string;
  /** Server-derived, set when the user's first target version is created. Never writable. **Do not route on this field alone**: a user who left onboarding without setting targets has `onboarding_skipped_at` instead, and routing them back to onboarding on every launch turns a supported exit into a nag. Route to Today when either field is set. */
  readonly onboarding_completed: boolean;
  /**
   * When the user chose to leave onboarding without setting targets, or null if they never did. Client-written through `PATCH /api/users/me/`, because a skip is a choice the server cannot derive. Read it together with `onboarding_completed`.
   * @nullable
   */
  readonly onboarding_skipped_at: string | null;
  readonly sex: (typeof UserSex)[keyof typeof UserSex];
  /**
   * @nullable
   * @pattern ^-?\d{0,4}(?:\.\d{0,2})?$
   */
  readonly current_weight_lb: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,4}(?:\.\d{0,2})?$
   */
  readonly goal_weight_lb: string | null;
  /** @nullable */
  readonly goal_timeline_weeks: number | null;
  /** @nullable */
  readonly training_days_per_week: number | null;
  readonly dietary_constraints: string;
}
