# Generated by Django 6.0.7 on 2026-09-01 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='analysis_call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_entry', to='ai.foodanalysiscall'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='photo_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
