# Generated by Django 6.0.7 on 2026-08-29 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('protein_g', models.IntegerField()),
                ('fiber_g', models.IntegerField()),
                ('source', models.CharField(choices=[('onboarding_ai', 'Onboarding (AI proposal)'), ('manual', 'Manual edit')], max_length=32)),
                ('ai_rationale', models.TextField(blank=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='targetversion_user_recent')],
            },
        ),
    ]
