# Generated by Django 6.0.7 on 2026-08-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetversion',
            name='ai_rationale',
            field=models.TextField(blank=True, help_text="The model's plain-English explanation, shown under WHY THESE NUMBERS on screen 9f. Around 60 words, naming the deficit, the rate, and why protein is set from body weight. Empty for a manual edit."),
        ),
    ]
